
name: 'olist_analytics'
version: '1.0.0'

profile: 'olist_analytics'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"



# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  olist_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
