version: 2

sources:
  - name: raw
    database: olist
    schema: main
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: payments
      - name: reviews
      - name: products
      - name: sellers